import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:quiz_app/ai/ai_capabilities.dart';
import 'package:quiz_app/ai/ai_service.dart';
import 'package:quiz_app/ai/default_ai_service.dart';
import 'package:quiz_app/ai/draft_validator.dart';
import 'package:quiz_app/ai/llm_provider.dart';
import 'package:quiz_app/ai/providers/default_llm_provider_factory.dart';
import 'package:quiz_app/ai/secure_api_key_store.dart';
import 'package:quiz_app/ai/transcript_service.dart';
import 'package:quiz_app/core/errors/app_exception.dart';

import 'test_helpers.dart';

class _Transcripts implements TranscriptService {
  final calls = <String>[];

  @override
  Future<VideoTranscript> fetchTranscript(String url) async {
    calls.add(url);
    return const VideoTranscript(
      videoId: 'dQw4w9WgXcQ',
      title: 'Cell biology 101',
      text: 'The mitochondria is the powerhouse of the cell.',
      isAutoGenerated: true,
    );
  }
}

final _note = {'title': 'Cells', 'content_markdown': '## A\n- b'};

Map<String, dynamic> _openAiText(Object json) => {
  'status': 'completed',
  'output': [
    {
      'type': 'message',
      'content': [
        {'type': 'output_text', 'text': jsonEncode(json)},
      ],
    },
  ],
};

Map<String, dynamic> _geminiText(Object json) => {
  'candidates': [
    {
      'content': {
        'parts': [
          {'text': jsonEncode(json)},
        ],
      },
      'finishReason': 'STOP',
    },
  ],
};

Map<String, dynamic> _chatText(Object json) => {
  'choices': [
    {
      'message': {'content': jsonEncode(json)},
      'finish_reason': 'stop',
    },
  ],
};

final _pdf = FileSource(
  name: 'notes.pdf',
  mimeType: 'application/pdf',
  bytes: Uint8List.fromList(utf8.encode('%PDF-1.7')),
);
final _png = FileSource(
  name: 'board.png',
  mimeType: null,
  bytes: Uint8List.fromList([1, 2, 3]),
);

Matcher _unsupported(Object message) => throwsA(
  isA<AiException>()
      .having((e) => e.kind, 'kind', AiErrorKind.unsupported)
      .having((e) => e.message, 'message', message),
);

void main() {
  late SecureApiKeyStore keys;
  late _Transcripts transcripts;

  setUp(() {
    keys = SecureApiKeyStore(userId: 'u1', backend: InMemoryKeyValueStore());
    transcripts = _Transcripts();
  });

  DefaultAiService service(
    RecordingClient rc, {
    bool isWeb = false,
    AiCapabilityResolver? capabilities,
    int maxContextChars = 100000,
  }) => DefaultAiService(
    keyStore: keys,
    providerFactory: DefaultLlmProviderFactory(rc.client, isWeb: isWeb),
    transcriptService: transcripts,
    capabilities: capabilities,
    isWeb: isWeb,
    maxContextChars: maxContextChars,
  );

  test('OpenAI: mixed sources -> labeled prompt + file/image parts', () async {
    await keys.setApiKey(LlmProviderId.openai, 'sk');
    final rc = RecordingClient([
      (_) => jsonResponse(_openAiText(validQuizJson(n: 2))),
    ]);
    final docx = buildDocx(
      '<w:p><w:r><w:t>Ribosomes build proteins.</w:t></w:r></w:p>',
    );
    await service(rc).generateQuiz(
      QuizGenerationRequest(
        contextText: 'Legacy pasted text',
        questionCount: 2,
        sources: [
          const NoteSource(title: 'Organelles', markdown: '# Nucleus\nDNA'),
          FileSource(name: 'lab.docx', mimeType: null, bytes: docx),
          _pdf,
          _png,
          const TextSource(text: '   '), // blank: dropped
        ],
      ),
    );
    final content =
        ((rc.requests.single.json['input'] as List).single as Map)['content']
            as List;
    expect(content.map((c) => (c as Map)['type']), [
      'input_text',
      'input_file',
      'input_text',
      'input_image',
      'input_text',
    ]);
    expect((content[0] as Map)['text'], 'Attachment 1: notes.pdf');
    expect((content[1] as Map)['filename'], 'notes.pdf');
    expect((content[2] as Map)['text'], 'Attachment 2: board.png');
    expect(
      (content[3] as Map)['image_url'],
      startsWith('data:image/png;base64,'),
    );
    final prompt = (content.last as Map)['text'] as String;
    expect(prompt, contains('Source material (5 sources'));
    expect(prompt, contains('Ground everything in these sources'));
    expect(prompt, contains('[Source 1] Text provided by the user:'));
    expect(prompt, contains('Legacy pasted text'));
    expect(prompt, contains('[Source 2] Note "Organelles":'));
    expect(prompt, contains('# Nucleus\nDNA'));
    expect(
      prompt,
      contains('[Source 3] Text extracted from the file "lab.docx":'),
    );
    expect(prompt, contains('Ribosomes build proteins.'));
    expect(
      prompt,
      contains('[Source 4] PDF document "notes.pdf" (Attachment 1)'),
    );
    expect(prompt, contains('[Source 5] Image "board.png" (Attachment 2)'));
    expect(prompt, contains('exactly 2 questions'));
  });

  test('text-only model + PDF -> unsupported, nothing sent', () async {
    await keys.setApiKey(LlmProviderId.openai, 'sk');
    await keys.setSelectedModel(LlmProviderId.openai, 'gpt-3.5-turbo');
    final rc = RecordingClient([(_) => jsonResponse({})]);
    await expectLater(
      service(rc).generateNote(NoteGenerationRequest(sources: [_pdf])),
      _unsupported(
        allOf(
          contains('gpt-3.5-turbo'),
          contains('PDF files'),
          contains('notes.pdf'),
        ),
      ),
    );
    expect(rc.requests, isEmpty);
  });

  test('audio with Anthropic -> unsupported, suggests Gemini', () async {
    await keys.setApiKey(LlmProviderId.anthropic, 'sk');
    final rc = RecordingClient([(_) => jsonResponse({})]);
    await expectLater(
      service(rc).generateNote(
        NoteGenerationRequest(
          sources: [
            FileSource(name: 'talk.mp3', mimeType: null, bytes: Uint8List(4)),
          ],
        ),
      ),
      _unsupported(allOf(contains('audio'), contains('Gemini'))),
    );
    expect(rc.requests, isEmpty);
  });

  test('unknown file type is rejected before reading settings', () async {
    final rc = RecordingClient([(_) => jsonResponse({})]);
    await expectLater(
      service(rc).generateNote(
        NoteGenerationRequest(
          sources: [
            FileSource(
              name: 'a.zip',
              mimeType: 'application/zip',
              bytes: Uint8List(4),
            ),
          ],
        ),
      ),
      _unsupported(contains('a.zip')),
    );
  });

  test('no usable sources / empty text file -> ValidationException', () async {
    await keys.setApiKey(LlmProviderId.openai, 'sk');
    final rc = RecordingClient([(_) => jsonResponse({})]);
    await expectLater(
      service(rc).generateNote(
        const NoteGenerationRequest(
          sources: [NoteSource(title: 'Empty', markdown: ' ')],
        ),
      ),
      throwsA(isA<ValidationException>()),
    );
    await expectLater(
      service(rc).generateNote(
        NoteGenerationRequest(
          sources: [
            FileSource(
              name: 'a.txt',
              mimeType: 'text/plain',
              bytes: Uint8List(0),
            ),
          ],
        ),
      ),
      throwsA(
        isA<ValidationException>().having(
          (e) => e.message,
          'message',
          contains('a.txt'),
        ),
      ),
    );
    expect(rc.requests, isEmpty);
  });

  test('Gemini: video inline + native YouTube, no transcript', () async {
    await keys.setApiKey(LlmProviderId.gemini, 'g');
    final rc = RecordingClient([(_) => jsonResponse(_geminiText(_note))]);
    await service(rc).generateNote(
      NoteGenerationRequest(
        sources: [
          FileSource(
            name: 'clip.mp4',
            mimeType: 'video/mp4',
            bytes: Uint8List(8),
          ),
          const YoutubeSource('https://youtu.be/dQw4w9WgXcQ'),
        ],
      ),
    );
    expect(transcripts.calls, isEmpty);
    final parts =
        ((rc.requests.single.json['contents'] as List).single as Map)['parts']
            as List;
    expect(parts[0], {'text': 'Attachment 1: clip.mp4'});
    expect((parts[1] as Map)['inlineData'], {
      'mimeType': 'video/mp4',
      'data': base64Encode(Uint8List(8)),
    });
    expect(parts[2], {'text': 'Attachment 2: YouTube video'});
    expect(parts[3], {
      'fileData': {'fileUri': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'},
    });
    final prompt = (parts[4] as Map)['text'] as String;
    expect(prompt, contains('[Source 1] Video "clip.mp4" (Attachment 1)'));
    expect(
      prompt,
      contains('[Source 2] The attached YouTube video (Attachment 2)'),
    );
  });

  test(
    'non-Gemini YouTube: transcript (labeled) on native, blocked on web',
    () async {
      await keys.setApiKey(LlmProviderId.openai, 'sk');
      final rc = RecordingClient([(_) => jsonResponse(_openAiText(_note))]);
      const request = NoteGenerationRequest(
        sources: [YoutubeSource('https://youtu.be/dQw4w9WgXcQ')],
      );
      await service(rc).generateNote(request);
      final input = rc.requests.single.json['input'] as String;
      expect(
        input,
        contains(
          '[Source 1] Transcript of the YouTube video "Cell biology 101" '
          '(auto-generated captions',
        ),
      );
      expect(input, contains('powerhouse'));

      await expectLater(
        service(rc, isWeb: true).generateNote(request),
        throwsA(
          isA<TranscriptUnavailableException>().having(
            (e) => e.message,
            'message',
            contains('Gemini'),
          ),
        ),
      );
      expect(transcripts.calls, hasLength(1));
      expect(rc.requests, hasLength(1));
    },
  );

  test('key-less local endpoint with manual image override', () async {
    await keys.setSelectedProvider(LlmProviderId.openaiCompatible);
    await keys.setBaseUrl(
      LlmProviderId.openaiCompatible,
      'http://localhost:11434/v1',
    );
    await keys.setSelectedModel(LlmProviderId.openaiCompatible, 'llava');
    final rc = RecordingClient([(_) => jsonResponse(_chatText(_note))]);

    await expectLater(
      service(rc).generateNote(NoteGenerationRequest(sources: [_png])),
      _unsupported(contains('Settings')),
    );

    await keys.setInputOverride(LlmProviderId.openaiCompatible, 'llava', {
      AiInputKind.image,
    });
    await service(rc).generateNote(NoteGenerationRequest(sources: [_png]));
    final r = rc.requests.single;
    expect(r.url.toString(), 'http://localhost:11434/v1/chat/completions');
    expect(r.headers.containsKey('authorization'), isFalse);
    final user = (r.json['messages'] as List).last as Map;
    expect(((user['content'] as List)[1] as Map)['type'], 'image_url');
  });

  test('OpenRouter capabilities via resolver allow PDFs', () async {
    await keys.setApiKey(LlmProviderId.openaiCompatible, 'sk-or');
    await keys.setSelectedModel(
      LlmProviderId.openaiCompatible,
      'google/gemini-3-flash',
    );
    final rc = RecordingClient([
      (_) => jsonResponse({
        'data': [
          {
            'id': 'google/gemini-3-flash',
            'architecture': {
              'input_modalities': ['text', 'image', 'file', 'audio', 'video'],
            },
          },
        ],
      }),
      (_) => jsonResponse(_chatText(_note)),
    ]);
    final resolver = AiCapabilityResolver(client: rc.client, isWeb: false);
    await service(
      rc,
      capabilities: resolver,
    ).generateNote(NoteGenerationRequest(sources: [_pdf]));
    expect(rc.requests, hasLength(2));
    expect(rc.requests[0].url.path, '/api/v1/models');
    final user = (rc.requests[1].json['messages'] as List).last as Map;
    expect(((user['content'] as List)[1] as Map)['type'], 'file');
  });

  test('text budget is shared fairly across text sources', () async {
    await keys.setApiKey(LlmProviderId.openai, 'sk');
    final rc = RecordingClient([(_) => jsonResponse(_openAiText(_note))]);
    await service(rc, maxContextChars: 100).generateNote(
      NoteGenerationRequest(
        sources: [
          TextSource(text: 'S' * 30),
          NoteSource(title: 'Long', markdown: 'L' * 200),
        ],
      ),
    );
    final input = rc.requests.single.json['input'] as String;
    expect(input, contains('${'S' * 30}\n</source>'));
    expect(input, contains('${'L' * 70}\n\n[Source truncated'));
    expect(input, isNot(contains('L' * 71)));
    expect(input, contains('first 70 of 200 characters'));
  });

  test('generateStructured: custom task/schema with repair retry', () async {
    await keys.setApiKey(LlmProviderId.openai, 'sk');
    final rc = RecordingClient([
      (_) => jsonResponse(_openAiText({'cards': <Object>[]})),
      (_) => jsonResponse(
        _openAiText({
          'cards': [
            {'front': 'ATP?', 'back': 'Energy'},
          ],
        }),
      ),
    ]);
    const schema = {
      'type': 'object',
      'properties': {
        'cards': {
          'type': 'array',
          'items': {
            'type': 'object',
            'properties': {
              'front': {'type': 'string'},
              'back': {'type': 'string'},
            },
            'required': ['front', 'back'],
          },
        },
      },
      'required': ['cards'],
    };
    final cards = await service(rc).generateStructured<List<Object?>>(
      const StructuredGenerationRequest(
        sources: [NoteSource(title: 'Energy', markdown: 'ATP stores energy')],
        task: 'Create flashcards (front/back).',
        systemPrompt: 'You write flashcards.',
        schema: schema,
        schemaName: 'Deck',
        topic: 'Biology',
      ),
      validate: (json) {
        final list = json['cards'];
        return list is List && list.isNotEmpty
            ? DraftValidation(list, const [])
            : const DraftValidation(null, ['cards is empty']);
      },
      what: 'deck',
    );
    expect(cards, hasLength(1));
    final first = rc.requests[0].json;
    expect(first['instructions'], 'You write flashcards.');
    expect((first['text'] as Map)['format'], containsPair('name', 'Deck'));
    final input = first['input'] as String;
    expect(input, startsWith('Create flashcards (front/back).'));
    expect(input, contains('Topic: Biology'));
    expect(input, contains('[Source 1] Note "Energy":'));
    expect(rc.requests[1].json['input'], contains('cards is empty'));
  });

  test('resolveSelection falls back to a key-less local endpoint', () async {
    await keys.setBaseUrl(
      LlmProviderId.openaiCompatible,
      'http://127.0.0.1/v1',
    );
    final s = service(RecordingClient([(_) => jsonResponse({})]));
    expect(
      (await s.resolveSelection()).providerId,
      LlmProviderId.openaiCompatible,
    );
  });
}
