import 'package:flutter_test/flutter_test.dart';
import 'package:quiz_app/ai/youtube_transcript_service.dart';
import 'package:quiz_app/core/errors/app_exception.dart';

class FakeCaptionSource implements CaptionSource {
  FakeCaptionSource({
    this.tracks = const [],
    this.lines = const {},
    this.title = 'A video',
    this.listError,
    this.titleError,
  });

  final List<CaptionTrackRef> tracks;
  final Map<String, List<String>> lines; // by languageCode + auto flag
  final String? title;
  final Object? listError;
  final Object? titleError;
  final requestedIds = <String>[];
  CaptionTrackRef? fetched;

  static String keyOf(CaptionTrackRef t) =>
      '${t.languageCode}${t.isAutoGenerated ? ':auto' : ''}';

  @override
  Future<List<CaptionTrackRef>> listTracks(String videoId) async {
    requestedIds.add(videoId);
    if (listError != null) throw listError!;
    return tracks;
  }

  @override
  Future<List<String>> fetchLines(CaptionTrackRef track) async {
    fetched = track;
    return lines[keyOf(track)] ?? const [];
  }

  @override
  Future<String?> fetchTitle(String videoId) async {
    if (titleError != null) throw titleError!;
    return title;
  }
}

const _url = 'https://youtu.be/dQw4w9WgXcQ';

void main() {
  test('prefers manual English, joins text, strips sound tags', () async {
    final source = FakeCaptionSource(
      tracks: const [
        CaptionTrackRef(languageCode: 'de'),
        CaptionTrackRef(languageCode: 'en', isAutoGenerated: true),
        CaptionTrackRef(languageCode: 'en-GB'),
      ],
      lines: {
        'en-GB': ['[Music] Hello', '  world\nagain  ', '[Applause]'],
        'en:auto': ['auto text'],
      },
    );
    final t = await YoutubeTranscriptService(
      source: source,
      isWeb: false,
    ).fetchTranscript(_url);
    expect(source.requestedIds.single, 'dQw4w9WgXcQ');
    expect(t.videoId, 'dQw4w9WgXcQ');
    expect(t.title, 'A video');
    expect(t.text, 'Hello world again');
    expect(t.languageCode, 'en-GB');
    expect(t.isAutoGenerated, isFalse);
    expect(t.truncated, isFalse);
  });

  test('track preference order', () {
    const manualDe = CaptionTrackRef(languageCode: 'de');
    const autoEn = CaptionTrackRef(languageCode: 'en', isAutoGenerated: true);
    const autoFr = CaptionTrackRef(languageCode: 'fr', isAutoGenerated: true);
    expect(
      YoutubeTranscriptService.pickTrack([manualDe, autoEn], 'en'),
      autoEn,
    );
    expect(
      YoutubeTranscriptService.pickTrack([autoFr, manualDe], 'en'),
      manualDe,
    );
    expect(YoutubeTranscriptService.pickTrack([autoFr], 'en'), autoFr);
  });

  test('truncates to the char budget with a note', () async {
    final words = List.filled(100, 'word').join(' '); // 499 chars
    final source = FakeCaptionSource(
      tracks: const [CaptionTrackRef(languageCode: 'en')],
      lines: {
        'en': [words],
      },
    );
    final t = await YoutubeTranscriptService(
      source: source,
      maxChars: 100,
      isWeb: false,
    ).fetchTranscript(_url);
    expect(t.truncated, isTrue);
    expect(t.text, contains('[Transcript truncated'));
    expect(t.text.split('\n\n').first.length, lessThanOrEqualTo(100));
    expect(t.text.split('\n\n').first.endsWith('word'), isTrue);
  });

  test('invalid URL -> ValidationException', () async {
    await expectLater(
      YoutubeTranscriptService(
        source: FakeCaptionSource(),
        isWeb: false,
      ).fetchTranscript('https://vimeo.com/1'),
      throwsA(isA<ValidationException>()),
    );
  });

  test(
    'no captions -> TranscriptUnavailableException mentioning Gemini',
    () async {
      await expectLater(
        YoutubeTranscriptService(
          source: FakeCaptionSource(),
          isWeb: false,
        ).fetchTranscript(_url),
        throwsA(
          isA<TranscriptUnavailableException>()
              .having((e) => e.message, 'msg', contains('no captions'))
              .having((e) => e.message, 'msg', contains('Gemini')),
        ),
      );
    },
  );

  test('private video -> TranscriptUnavailableException', () async {
    final source = FakeCaptionSource(titleError: const VideoUnavailableError());
    await expectLater(
      YoutubeTranscriptService(
        source: source,
        isWeb: false,
      ).fetchTranscript(_url),
      throwsA(
        isA<TranscriptUnavailableException>().having(
          (e) => e.message,
          'msg',
          contains('private'),
        ),
      ),
    );
  });

  test('on web any failure suggests Gemini', () async {
    final source = FakeCaptionSource(
      listError: Exception('XMLHttpRequest error'),
    );
    await expectLater(
      YoutubeTranscriptService(
        source: source,
        isWeb: true,
      ).fetchTranscript(_url),
      throwsA(
        isA<TranscriptUnavailableException>()
            .having((e) => e.message, 'msg', contains('browser'))
            .having((e) => e.message, 'msg', contains('Gemini')),
      ),
    );
  });

  test('rate limiting is reported clearly', () async {
    final source = FakeCaptionSource(
      listError: const CaptionRateLimitedError(),
    );
    await expectLater(
      YoutubeTranscriptService(
        source: source,
        isWeb: false,
      ).fetchTranscript(_url),
      throwsA(
        isA<TranscriptUnavailableException>().having(
          (e) => e.message,
          'msg',
          contains('limiting'),
        ),
      ),
    );
  });
}
