/// Transcript of a YouTube video.
class VideoTranscript {
  const VideoTranscript({
    required this.videoId,
    required this.text,
    this.title,
    this.languageCode,
    this.isAutoGenerated = false,
    this.truncated = false,
  });

  final String videoId;
  final String? title;

  /// Plain caption text (no timestamps).
  final String text;
  final String? languageCode;

  /// Whether the captions were auto-generated by YouTube (lower accuracy).
  final bool isAutoGenerated;

  /// Whether [text] was cut to the service's character budget (a note is
  /// appended to [text] in that case).
  final bool truncated;
}

/// Fetches YouTube captions client-side (used for non-Gemini providers).
abstract interface class TranscriptService {
  /// Throws `ValidationException` for an invalid URL and
  /// `TranscriptUnavailableException` when there are no captions or the
  /// request is blocked (e.g. CORS on web).
  Future<VideoTranscript> fetchTranscript(String url);
}
