import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:http/http.dart' as http;
import 'package:youtube_explode_dart/youtube_explode_dart.dart' as yt;

import '../core/errors/app_exception.dart';
import 'transcript_service.dart';
import 'youtube_url.dart';

/// One available caption track (source-agnostic so tests can fake it).
class CaptionTrackRef {
  const CaptionTrackRef({
    required this.languageCode,
    this.languageName = '',
    this.isAutoGenerated = false,
    this.handle,
  });

  final String languageCode;
  final String languageName;
  final bool isAutoGenerated;

  /// Source-specific object needed to download the track.
  final Object? handle;
}

/// Thrown by a [CaptionSource] when the video is private/removed/unplayable.
class VideoUnavailableError implements Exception {
  const VideoUnavailableError([this.reason]);
  final String? reason;
}

/// Thrown by a [CaptionSource] when YouTube rate-limits the client.
class CaptionRateLimitedError implements Exception {
  const CaptionRateLimitedError();
}

/// Low-level caption access. Default: [YoutubeExplodeCaptionSource].
abstract interface class CaptionSource {
  Future<List<CaptionTrackRef>> listTracks(String videoId);
  Future<List<String>> fetchLines(CaptionTrackRef track);

  /// Video title, or null if unknown. Throws [VideoUnavailableError] for
  /// private/removed videos.
  Future<String?> fetchTitle(String videoId);
}

/// [CaptionSource] backed by `youtube_explode_dart` (a fresh client per
/// call, closed afterwards).
class YoutubeExplodeCaptionSource implements CaptionSource {
  YoutubeExplodeCaptionSource({this.httpClientFactory});

  /// Optional HTTP client factory (e.g. for a proxy); default client if null.
  final http.Client Function()? httpClientFactory;

  Future<T> _run<T>(Future<T> Function(yt.YoutubeExplode client) body) async {
    final factory = httpClientFactory;
    final client = yt.YoutubeExplode(
      httpClient: factory == null ? null : yt.YoutubeHttpClient(factory()),
    );
    try {
      return await body(client);
    } on yt.RequestLimitExceededException {
      throw const CaptionRateLimitedError();
    } on yt.VideoUnplayableException catch (e) {
      throw VideoUnavailableError(e.message);
    } finally {
      client.close();
    }
  }

  @override
  Future<List<CaptionTrackRef>> listTracks(String videoId) => _run((c) async {
    final manifest = await c.videos.closedCaptions.getManifest(
      videoId,
      formats: const [yt.ClosedCaptionFormat.srv3],
    );
    return [
      for (final t in manifest.tracks)
        CaptionTrackRef(
          languageCode: t.language.code,
          languageName: t.language.name,
          isAutoGenerated: t.isAutoGenerated,
          handle: t,
        ),
    ];
  });

  @override
  Future<List<String>> fetchLines(CaptionTrackRef track) => _run((c) async {
    final info = track.handle! as yt.ClosedCaptionTrackInfo;
    final captions = await c.videos.closedCaptions.get(info);
    return [for (final cap in captions.captions) cap.text];
  });

  @override
  Future<String?> fetchTitle(String videoId) =>
      _run((c) async => (await c.videos.get(videoId)).title);
}

/// [TranscriptService] that downloads YouTube captions client-side.
///
/// Track choice: manual English, else auto-generated English, else the
/// first manual track, else the first track. Text is joined into plain
/// prose (sound tags like `[Music]` removed) and cut to [maxChars] with a
/// note.
///
/// On web, YouTube usually blocks these requests (CORS); failures are
/// reported as [TranscriptUnavailableException] suggesting Gemini, which
/// reads YouTube videos directly.
class YoutubeTranscriptService implements TranscriptService {
  YoutubeTranscriptService({
    CaptionSource? source,
    this.maxChars = 60000,
    this.preferredLanguage = 'en',
    bool? isWeb,
  }) : _source = source ?? YoutubeExplodeCaptionSource(),
       _isWeb = isWeb ?? kIsWeb;

  final CaptionSource _source;
  final bool _isWeb;

  /// Character budget for the returned transcript text.
  final int maxChars;

  /// Language code preferred when several tracks exist.
  final String preferredLanguage;

  static const _useGeminiHint =
      'Paste the content as text instead, or switch to Gemini, which can '
      'watch YouTube videos directly.';

  @override
  Future<VideoTranscript> fetchTranscript(String url) async {
    final videoId = YoutubeUrl.parseVideoId(url);
    if (videoId == null) {
      throw const ValidationException(
        "That doesn't look like a YouTube video link.",
      );
    }
    try {
      final tracks = await _source.listTracks(videoId);
      if (tracks.isEmpty) {
        // Distinguish "private/removed" from "no captions".
        await _source.fetchTitle(videoId);
        throw const TranscriptUnavailableException(
          'This video has no captions, so its transcript cannot be read. '
          '$_useGeminiHint',
        );
      }
      final track = pickTrack(tracks, preferredLanguage);
      final lines = await _source.fetchLines(track);
      final full = joinCaptionLines(lines);
      if (full.isEmpty) {
        throw const TranscriptUnavailableException(
          "This video's captions are empty. $_useGeminiHint",
        );
      }
      String? title;
      try {
        title = await _source.fetchTitle(videoId);
      } catch (_) {
        title = null; // title is optional
      }
      final (text, truncated) = truncateTranscript(full, maxChars);
      return VideoTranscript(
        videoId: videoId,
        title: title,
        text: text,
        languageCode: track.languageCode,
        isAutoGenerated: track.isAutoGenerated,
        truncated: truncated,
      );
    } on AppException {
      rethrow;
    } on VideoUnavailableError catch (e, st) {
      throw TranscriptUnavailableException(
        'This video is private, age-restricted or unavailable, so its '
        'transcript cannot be read.',
        cause: e,
        stackTrace: st,
      );
    } on CaptionRateLimitedError catch (e, st) {
      throw TranscriptUnavailableException(
        'YouTube is limiting requests right now. Try again later. '
        '$_useGeminiHint',
        cause: e,
        stackTrace: st,
      );
    } catch (e, st) {
      if (_isWeb) {
        throw TranscriptUnavailableException(
          'Your browser blocked reading the YouTube transcript. '
          '$_useGeminiHint',
          cause: e,
          stackTrace: st,
        );
      }
      if (e is http.ClientException) {
        throw NetworkException(
          "Couldn't reach YouTube. Check your internet connection.",
          cause: e,
          stackTrace: st,
        );
      }
      throw TranscriptUnavailableException(
        "Couldn't read this video's transcript. $_useGeminiHint",
        cause: e,
        stackTrace: st,
      );
    }
  }

  /// Manual [preferred] > auto [preferred] > first manual > first.
  static CaptionTrackRef pickTrack(
    List<CaptionTrackRef> tracks,
    String preferred,
  ) {
    bool matches(CaptionTrackRef t) {
      final code = t.languageCode.toLowerCase();
      final p = preferred.toLowerCase();
      return code == p || code.startsWith('$p-') || code.startsWith('${p}_');
    }

    return tracks.firstWhere(
      (t) => matches(t) && !t.isAutoGenerated,
      orElse: () => tracks.firstWhere(
        matches,
        orElse: () => tracks.firstWhere(
          (t) => !t.isAutoGenerated,
          orElse: () => tracks.first,
        ),
      ),
    );
  }

  static final _soundTag = RegExp(r'\[[^\]]{1,40}\]');
  static final _whitespace = RegExp(r'\s+');

  /// Joins caption lines into a single paragraph-ish string.
  static String joinCaptionLines(Iterable<String> lines) => lines
      .map((l) => l.replaceAll(_soundTag, ' '))
      .join(' ')
      .replaceAll(_whitespace, ' ')
      .trim();

  /// Cuts [text] to at most [maxChars] (at a word boundary) and appends a
  /// note. Returns the text and whether it was truncated.
  static (String, bool) truncateTranscript(String text, int maxChars) {
    if (text.length <= maxChars) return (text, false);
    var cut = text.lastIndexOf(' ', maxChars);
    if (cut < maxChars * 0.8) cut = maxChars;
    final kept = text.substring(0, cut).trimRight();
    return (
      '$kept\n\n[Transcript truncated: showing the first ${kept.length} of '
          '${text.length} characters.]',
      true,
    );
  }
}
